import { chromium } from 'playwright';
const S = '/tmp/claude-0/-home-user-shop-intoto/c8d8d7a8-706d-5479-a974-7bf55eb691c3/scratchpad/';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1500, height: 1000 } });
const errs = [];
p.on('pageerror', (e) => errs.push('PAGEERROR: ' + e.message));
p.on('console', (m) => { if (m.type()==='error') errs.push(m.text()); });
await p.goto('http://127.0.0.1:4199/');
await p.waitForSelector('#gate-name', { timeout: 15000 });
await p.fill('#gate-name','Abdul Rahman');
await p.click('button:has-text("Start")');
await p.waitForSelector('.kpis', { timeout: 15000 });
await p.waitForTimeout(900);
const cards = await p.$$eval('.content section.card header h2', n => n.map(x=>x.textContent));
console.log('DASHBOARD CARDS:', cards.join(' | '));
console.log('Registers table removed:', cards.includes('Registers') ? 'NO — still there' : 'yes');
await p.screenshot({ path: S + '60-dashboard-final.png', fullPage: true });
console.log('CONSOLE ERRORS:', errs.length ? errs.join('\n') : 'none');
await b.close();
